More human readable dump
neobrain/braindump pull request #34
Opened 2017-02-22 08:42 UTC by RiderExMachina

I made it so it's in MiB instead of KiB. Makes the game sizes more human readable and understandable. I also tried writing a percentage calculator, but that seems to be having a few minor difficulties. You can see those at 360 of main.cpp

2017-02-22 11:33 UTC, InusualZ requested changes

2017-02-22 11:33 UTC, InusualZ commented on README.md
> +Forked from neobrain. See the original project at [https://github.com/neobrain/braindump](https://github.com/neobrain/braindump)
This is not needed since it's the original project

2017-02-22 11:33 UTC, InusualZ commented on source/main.cpp
> +		std::cout << (size / 1024) << " KiB... " << std::flush;
You broke the format. Ditto for below

2017-02-23 04:11 UTC, RiderExMachina commented on README.md
> +Forked from neobrain. See the original project at [https://github.com/neobrain/braindump](https://github.com/neobrain/braindump)
Heh, yeah. Didn't know how to remove that from the commit

2017-02-23 04:12 UTC, RiderExMachina commented on source/main.cpp
> +		std::cout << (size / 1024) << " KiB... " << std::flush;
Ah, okay. I'll be more careful in the future

2017-03-12 00:58 UTC, neobrain commented
Thanks for the pull request, and sorry for the late reply - this PR slipped somehow slipped my inbox queue and I just accidentally "discovered" it.

Anyway, to get this merged, please:
* Fix the formatting. There are some improper whitespace changes that should be easy to fix by looking at how the existing code is formatted
* Merge your patches into a single one
* Drop the Readme change from this PR. It's unrelated and hence should go into a separate PR (but since it's a simple change, I just edited the Readme manually so you don't need to provide a separate PR in this instance)
* Fix the grammar and spelling mistakes in the code comments

2017-03-13 22:58 UTC, closed without merging